### ISSUE TITLE
es6 imports

### ISSUE THREAD

**Issue by doug** [Polymer/polymer-editor-service#12]
Would be great to make the polymer editor service understand es6 imports. Currently it returns an error: 'import' and 'export' may appear only with 'sourceType: module'

I understand HTMLImports and ES6 modules are still in the process of being developed, so maybe this issue is too soon.

**Comment by rictic** [comment]
At the least we shouldn't warn on imports unless we have positive information that the script is being loaded as a non-module.

Maybe we should always parse as a module, and add linters that will warn if you use an import or an export in the wrong kind of script.

**Comment by rictic** [comment]
Alternatively, we could try to parse each js file as a script, then if that fails try to parse it as a module; store which way that we parsed it; then warn at the resolve step if you reference a module as a script or vice versa.
