### ISSUE TITLE
When a file that didn't exist suddenly does, we still report it as missing

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-editor-service#14]
e.g. if you have imports into a bower directory but you haven't run `bower install` yet, your editor will report that the files are missing until you restart it because we cache that these files don't exist.

One elegant solution I've noticed that typescript uses to handle this efficiently is to recheck imports whenever a new import is added to the document. Alternatively, we could use something like `chokidar` to watch the filesystem and respond appropriately to changes. We could also expose the `_clearCaches` method in editors for this use case, but I would very much like to avoid this if possible, or at least only use it as a last ditch option.

**Comment by TimvdLippe** [comment]
Watching the files is the cleanest option in my opinion. Today I was encountering this issue and luckily it was just 3 imports, however I had to close Atom and reopen it and make some edits in these 3 bower files before it was refreshed.

**Comment by oneezy** [comment]
Same issue going on over here using `VScode (v1.7.2)` and `Polymer-IDE (v0.1.2)`

Any WIP going on for this? It's not super critical just one of those little annoyances :grin:

**Comment by rictic** [comment]
This one's a bit tricky. Will get solved, but it'll take a little while. Easiest solution in vscode and atom is to run the `> Reload Window` command

**Comment by oneezy** [comment]
ahhhh, i've been wondering what the reload command for VS was!... in Atom i was so use to hitting the `Ctrl+Shift+F5` ..and i'm still pretty fresh in moving around in VS, but I'm liking it way more.

That'll work
