### ISSUE TITLE
Duplicated html import seemed to flood output with error code 32603

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer-editor-service#16]
I accidentally included a duplicate html import of one of my own behaviors and got the following error message flooding the output (presumably when I moused over something) At one point I was getting just over 1 per second of these.

```
[Error - 17:56:29] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Expected to find at most one behavior with id PAS.DateUtils but found 2.
  Code: -32603 
```

Using vscode

**Comment by rictic** [comment]
The (super annoying!) popups will be fixed by https://github.com/Polymer/vscode-plugin/pull/21

That also should emit a lint-style warning rather than throwing. Filed that as https://github.com/Polymer/polymer-analyzer/issues/367

I haven't been able to reproduce two HTML imports producing that error though. Can you give more info about that, or maybe create a repro I can check out?

**Comment by akc42** [comment]
I just found it happening again.  I don't have two imports in the file, although the pluggin reported that.  What I was doing at the time was using the mouse wheel to scroll rapidly to the top of the file.  

The other important characteristic was that again it reported the problem on importing a **behavior.**

**Comment by akc42** [comment]
Now I have triggered it if I mouse over anything with link to something else (including the href on a lazy-import) it fires the same error message (ie related to double importing behavior)

If I switch away to another file, it doesn't happen on that other file, but if I switch back to the same file it continues to happen.

I restarted vscode and the problem went away.

**Comment by rictic** [comment]
Can you upload your repo in its current state somewhere and link me to a commit and the filename where you're noticing this problem?

**Comment by akc42** [comment]
@rictic I don't really want to make this repository public, but I can set something up which only you can acccess.

Email me an ssh public key and I will set up a repository  for a short while 
`rictic@asgard.hartley-consultants.com:pasv5.git` 
which you can clone.  I have made one commit since the second occurrence I mention above.

The repository is 220M big, so only access it on a sensible connection

**Comment by rictic** [comment]
No problem. Email sent.

**Comment by akc42** [comment]
@rictic set up (after I dug your e-mail out of junk :-))

**Comment by rictic** [comment]
This should be fixed at master.
