### ISSUE TITLE
script tag inside html src attributes file path being wrongly calculated

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer-editor-service#17]
I have project directory structure as the following

`/home/alan/dev/pasv5` as root of project
`/home/alan/dev/pasv5/app` as route of client app
`/home/alan/dev/pasv5/app/src` as directory as where my alements are stored
`/home/alan/dev/pasv5/app/scripts` as directory where one or two javascript files are storeed

Inside an an element in my element directory I have a script tag so
`<script src="../scripts/pikaday.js"></script>`
src attribute has the link with a red line under it.  When I mouse over it I get the error no such file or directory , open `/home/alan/dev/pasv5/scripts/pickaday.js` ie it has lost the `app` directory from the path.

**Comment by rictic** [comment]
I've tried to reproduce this here: https://github.com/rictic/repro-pes-17

But everything appears to work correctly. Can you give more info? What editor and OS are you using? Does the above repro work for you?

**Comment by akc42** [comment]
I'm not in a very convenient place to do much right now, but just a quick comment.

The relevant script tag was inside an html import and inside the `<dom-module id="my-element">` defining the element.  It was outside the `<template>` just above the `<script>` tag that held the `Polymer({is: 'my-element'}) inline code.  This file was inside the `src` directory defined above.

I was running vscode where the root of it was at `/home/alan/dev/pasv5`.  Running Debian Linux. 

This may be totally unrelated, and maybe more to do with the issue about absolute urls, but I am currently sitting in vscode on a mac with my index.html file located at `/home/alan/dev/pasv5/app/index.html` and in there I need to change the import to my app shell `<link rel="import" href="/src/pas-app.html" >` when I mouse over the href it shows an error saying it can't find the file at `/home/alan/dev/pasv5/src/pas-app.html` (I tried making all my url links relative because of the absolute url issue - but I am now falling foul of the app failing to start when I try and start on a route and the server returns index.html regardless - )
