### ISSUE TITLE
It would be nice if ../ always meant "look at the bower directory"

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-editor-service#2]
> Migrated from https://github.com/Polymer/atom-plugin/issues/3
> On September 29th, 2016, @notwaldorf said:

Context: if you have an enormous folder with a billion elements in it because you work on Polymer Elements and that's how you cope, auto-complete looks at the sibling directories rather than the bower deps, which may be woefully out of date.

**Comment by LostInBrittany** [comment]
It's a problem for users (in any editor, VSCode, Atom or Sublime) that deals with lots of components and prefers to open the big parent folder, yeah. Specially when not all the dependant elements are in sibling directories, as in Polymer/vscode-plugin#18.

**Comment by rictic** [comment]
Yeah, this would make the editors easier to use and less fragile, as you wouldn't have to make your workspace root exactly right.

We could keep the current behavior for the analyzer by adding a new URL resolver that searches for a bower_components directory when resolving a ../ URL anywhere.

**Comment by LostInBrittany** [comment]
Actually the analyzer already does that:

In `package-url-resolver.js`:
```
        // If the path points to a sibling directory, resolve it to the
        // component directory
        if (pathname.startsWith('../')) {
            pathname = path_1.posix.join(this.componentDir, pathname.substring(3));
        }
```

But it needs a relative path beginning with `..` . And in the vscode plugin (and I suspect in the others too), you're making everything relative to workspace root. And if you have a big folder with lots of elements insides, a link `../element` in a project `project` inside `workspace_root` becomes `workspace_root/element`.

**Comment by LostInBrittany** [comment]
In the analyzer side you don't even get the `../` as path are computed before in client-side and made relative to `workspaceRoot`

**Comment by justinfagnani** [comment]
@rictic I need to understand what's going on here. The PackageUrlResolver should already be doing this.

**Comment by rictic** [comment]
`PackageUrlResolver` only does that rewriting when the path is reaching out of the basedir. This is a proposal for doing it opportunistically, whenever it looks like it would help.

**Comment by oneezy** [comment]
Yeah..when attempting to `ctrl + click` on any `../` bower_components url, it doesn't know how to find it.

-----

Here's a screenshot of the bug in VScode:

![image](https://cloud.githubusercontent.com/assets/7369575/20783382/29e96ef8-b759-11e6-9967-d0855c7eb365.png)

**Comment by bashmish** [comment]
@rictic any updates on this? Do you use any workarounds to live with this limitation and still be able to use this Jump To Definition feature?
