### ISSUE TITLE
Documentation is not refreshed when modified

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-editor-service#21]
After you modify the documentation of an element, `getDocumentationAtPosition` called in a different file does not refresh. I am currently working on the documentation tooltip. The tooltip is showing the documentation of `vanilla.js` correctly. After I modified the documentation of `vanilla.js`, going back to the `index.html` the tooltip does not reflect the new value of the documentation. I have to close `index.html` and reopen the file to be able to refresh the documentation.

**Comment by rictic** [comment]
Oh, interesting, yeah I was able to reproduce this in vscode as well. So this should work if you modify index.html after modifying vanilla.js (as a temporary workaround), but this is a bug in the analyzer. We recently added some more caching and we're not doing cache expiry correctly based on dependencies, as we should throw out the cache of index.html when you modify vanilla.js.

Filed as https://github.com/Polymer/polymer-analyzer/issues/369 in the analyzer.
