### ISSUE TITLE
Editing .env file in project root and vscode plugin reported error

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer-editor-service#22]
I have a dot-env file in my project route (`.env`) which I started to edit.  vscode polymer-ide plugin reported following error

```
[Error - 23:47:38] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: No parser for for file type 
  Code: -32603 
```

this.env file is full of assignments like

MY_PCODE=xxx

It occurs as I start to edit one of these

**Comment by akc42** [comment]
Actually its also occurring when mouse hovers over any text

**Comment by rictic** [comment]
This is https://github.com/Polymer/vscode-plugin/issues/25 - it will be fixed in the next release of the vscode plugin. Eta tomorrow.
