### ISSUE TITLE
Support for Intellij

### ISSUE THREAD

**Issue by runia1** [Polymer/polymer-editor-service#43]
Making a plugin for intellij ide's would be nice.  The company I'm with uses phpstorm exclusively.  As did the last place I worked.

**Comment by web-padawan** [comment]
Vote fo this [feature request](https://youtrack.jetbrains.com/issue/IDEABKL-7409) then. This needs to having Language Server Protocol implemented by Intellij products.

**Comment by qertis** [comment]
+1

**Comment by laoshaw** [comment]
+1

**Comment by TrentBrown** [comment]
+1

**Comment by rictic** [comment]
The issue is on intellij's end. Please upvote this issue to let them know that this is important! https://youtrack.jetbrains.com/issue/IDEABKL-7409

**Comment by rictic** [comment]
There's a community plugin adding LSP support to intellij. I tried it out and attempted to get it working. Issue here with details: https://github.com/gtache/intellij-lsp/issues/12

**Comment by petecarapetyan** [comment]
+1

**Comment by vision-4** [comment]
+1
