### ISSUE TITLE
websocket: possibly add this as a new connection type?

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer-editor-service#47]
not sure what the long term plans for the project are, but if you plan to possibly hook this to up directly to a vscode editor running in the browser, say monaco. another transport would be ideal, say, WebSocket.

meaning, in the long term, do you want to this work only via vscode?

**Comment by rictic** [comment]
We definitely want to support every editor we can. Would be happy to add websocket support if there's an in-browser editor that speaks LSP.

**Comment by rictic** [comment]
Happy to add support for any transport. Just a few lines of code needed. I'd want to see an editor that needs the transport though, so I can do an end to end test with it.
