### ISSUE TITLE
Plugin for Chrome DevTools

### ISSUE THREAD

**Issue by JosefJezek** [Polymer/polymer-editor-service#50]
Could you create plugin for Chrome DevTools? I would like using DevTools as main editor.

DevTools is powerfull visual editor now...

- https://umaar.com/dev-tips/
- https://www.youtube.com/watch?v=N33lYfsAsoU
- https://developer.chrome.com/devtools/docs/extensions-gallery
- https://developers.google.com/web/tools/chrome-devtools/

**Comment by rictic** [comment]
That would be awesome. I'd love to bring whatever features we could to the chrome devtools, whether it's autocomplete, diagnostics, docs on hover, any of it, we'd love to make that work.

@paulirish

**Comment by qertis** [comment]
+!1

**Comment by JosefJezek** [comment]
@rictic @paulirish We have Workspaces 2.0 now. Do you plan Polymer IDE plugin for DevTools?

**Comment by JosefJezek** [comment]
@rictic @paulirish Could I use Workspaces 2.0 on Chromebook?

**Comment by paulirish** [comment]
@JosefJezek it wasn't explicitly tested, but hypothetically it should work.

**Comment by rictic** [comment]
Where can I read more about Workspaces 2.0?

Has anyone investigated LSP support in DevTools workspaces?

**Comment by JosefJezek** [comment]
@rictic https://developers.google.com/web/updates/2017/10/devtools-release-notes#workspaces

What is LSP?

**Comment by rictic** [comment]
It's the protocol that the polymer-editor-service (and increasingly many other tools) uses.

It's primarily designed for text editing, but it has other uses too.

https://github.com/Microsoft/language-server-protocol

**Comment by JosefJezek** [comment]
@paulirish Do you plan the LSP support in DevTools?

**Comment by JosefJezek** [comment]
@paulirish any progress
