### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-editor-service#7]
None of the editor plugins work on windows D:

Probably something with paths. Will take a look once I'm back at my windows machine.

**Comment by cgriffin4** [comment]
Windows path was broken when polymer-cli launched as well, https://github.com/Polymer/polymer-cli/pull/199.

Though, I'm not sure if it's related. The error I receive looks to have the correct path save for a duplicated drive. Path 'c:\c:\inetpub\proejct...' doesn't exist.

**Comment by ralcar** [comment]
Was so exited to try this after the Polymer Summit talk..
Tried to make it run in both VSCode and Atom this morning (in Windows 10), didnt work on any of them.
Must say that i am kind of surprised nobody bothered to test if it worked on Windows?!

**Comment by jared-unify** [comment]
I got mine to install by changing in package.json -> scripts -> clean from 
"mkdir -p lib/ && rm -rf lib/ && mkdir -p lib/test && cp -r src/test/static lib/test/"
to
"if not exist lib mkdir lib/ && rmdir /s /q lib/ && if not exist lib/test mkdir lib/test && cp -r src/test/static lib/test/"

**Comment by rictic** [comment]
So it looks like none of the issues (that I've been able to track down so far at least) are at the editor-service level, they're plugin-specific.
