### ISSUE TITLE
Unable to resolve behavior `Polymer.NoteAppBehavior` on VS Code

### ISSUE THREAD

**Issue by isorna** [Polymer/polymer-editor-service#8]
Hi there, maybe this is a bug, I'm not sure. 

Testing with the original https://github.com/PolymerLabs/note-app-elements code, and following the [polymer-firebase-pwa](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Fpolymer-summit-2016&viewga=UA-39334307-12#0) codelab, seems that this behavior is not recognized, as pictured:

![captura de pantalla 2016-10-18 a las 14 44 56](https://cloud.githubusercontent.com/assets/39324/19480286/b7caef74-9541-11e6-9d31-305ba4775f6b.png)

If I add this to the na-behavior.html, sometimes it doesn't show up, but as soon as I switch tabs from na-behavior.html to note-app.html or any other, the warning appears:

```
   /** 
    * @polymerBehavior
    */
```
I've uploaded my finished code here, following the codelab:
https://github.com/isorna/firebase-codelab

**Comment by sheeeng** [comment]
I experienced the same issue on Atom too.

```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm view polymer-ide
polymer-ide
├── 0.1.3
├── https://github.com/polymer/atom-plugin
├── Provides linting, autocompletion, and more for web components.
├── 78 downloads
└── 1 star

Run `apm install polymer-ide` to install this package.
```

![](http://i.imgur.com/b5yFO6t.png)

**Comment by rictic** [comment]
So I think that there were two issues that we ran into here. The first is that NoteAppBehavior isn't annotated with `@polymerBehavior` and the second is that the analyzer isn't generating warnings for transitive missing behaviors. Sent out a PR for the first, and filed this issue for the second: https://github.com/Polymer/polymer-analyzer/issues/361
